language: ruby
rvm:
- 2.1.0
before_script: gem install jekyll
script: jekyll build --destination out
notifications:
  flowdock:
    secure: "CNb/YjyuPmKnhHx7rMCLDALiylQAxMWzjkkGqTzuxOZAaAw3/desevn0E1XmLwhf1tmViWTNUSdTbspudBlEqylFes4NOrzuOfKrM0PMS+HUHPheqNm3si4R5R3eBiKeDXEELoX7TN6RyAtaSKn5lJDXFQfiH2Y5DIzx+tj3008="
deploy:
  provider: s3
  access_key_id: AKIAIKMGWFVFS3T2E3EA
  bucket: learn.stockflare.com
  skip_cleanup: true
  local-dir: out
  edge: true
  region: us-east-1
  endpoint: s3-us-east-1.amazonaws.com
  on:
    branch: master
  secret_access_key:
    secure: "Iy/9bthbslrmUks8Ym63EjSc9bx61kP8lU17RR8m7jhuFjKNpnrkWtO8KtQnPMM/bC9LtedwQynwTfMatG3J5TYvrYMujNIXKFz5fTW45CMUfZomJH8P/8SNkBRk2qWwx9nic+Nblvc12gknQLoBtGEbrPGjUSDQ+tQQiGyXCYM="
