# Site settings
title: Stockflare Learn
email: info@stockflare.com
description: > # this means to ignore newlines until "baseurl:"
  Learn how to use Stockflare to find your next idea. We also provide
  screencasts on how to get setup with a brokerage account and making your
  first investment
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://learn.stockflare.com"
twitter_username: stockflare
github_username:  Stockflare
